### PR TITLE
Appending orderby fields to select for mysql driver as well

### LINKED ISSUE #37: Error with order by and mysql 5.7
Hello,
First of all, thanks for this repository, it's a life saver for an old project that I cannot move to new doctrine versions.
I have a problem with a complex query that involves many left joined models and the order by clause.
When running a select I receive an error like this:
"General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'erp.a7.descr' which is not in SELECT list; this is incompatible with DISTINCT"

Doing some research I noticed that this is due to some restrictions made in mysql 5.7 and this seems to be already handled in doctrine 2 (https://github.com/doctrine/doctrine2/issues/5622).

Do you think it can be fixed for this repo? 
Thanks,
Frank

### PR DESCRIPTION
**Pull request by jaydiablo**
Fixes #37.

As discussed in the ticket, mysql 5.7 with the only_full_group_by option enabled (which is the default) requires that any fields used in the order by are used in the select (when DISTINCT is used).

Doctrine already has this logic in place for other drivers (as it's standard SQL), so just adding mysql to that list.

Also noticed that there was still some extra whitespace in one of the files I touched (on blank lines), so added the php-cs-fixer rule for that and updated all files (can hide those changes by adding `w=1` to the github query string when viewing the PR's changes).

### CODE REVIEW

File: .php_cs [hunk 1]
```diff
@@ -18,7 +18,8 @@ return PhpCsFixer\Config::create()
         'single_quote' => true,
         'array_syntax' => ['syntax' => 'long'],
         'concat_space' => ['spacing' => 'one'],
-        'psr0' => true
+        'psr0' => true,
+        'no_whitespace_in_blank_line' => true,
```
Comment (jaydiablo) [inline .php_cs]: non-whitespace change here

File: lib/Doctrine/Query.php [hunk 2]
```diff
@@ -1436,7 +1436,10 @@ public function getLimitSubquery()
         $subquery .= $this->_conn->quoteIdentifier($primaryKey);
 
         // pgsql & oracle need the order by fields to be preserved in select clause
-        if ($driverName == 'pgsql' || $driverName == 'oracle' || $driverName == 'oci' || $driverName == 'mssql' || $driverName == 'odbc') {
+        // Technically this isn't required for mysql <= 5.6, but mysql 5.7 with an sql_mode option enabled
+        // (only_full_group_by, which is enabled by default in 5.7) will throw SQL errors if this isn't done,
+        // so easier to just enable for all of mysql.
+        if ($driverName == 'mysql' || $driverName == 'pgsql' || $driverName == 'oracle' || $driverName == 'oci' || $driverName == 'mssql' || $driverName == 'odbc') {
```
Comment (jaydiablo) [inline lib/Doctrine/Query.php]: non-whitespace change here (this is the change that fixes #37)

File: tests/Query/OrderbyTestCase.php [hunk 3]
```diff
@@ -35,13 +35,14 @@ class Doctrine_Query_Orderby_TestCase extends Doctrine_UnitTestCase
     public function testOrderByRandomIsSupported()
```
Comment (jaydiablo) [inline tests/Query/OrderbyTestCase.php]: non-whitespace changes in this file are just fixing some type-os (I was going to add a test to this file for #37, but ended up not needing to).

File: tests/Query/MysqlSubqueryTestCase.php [hunk 4]
```diff
@@ -66,8 +67,9 @@ public function testGetLimitSubquerySupportsOrderByWithAggregateValuesAndDescKey
 
         $this->dbh->pop();
 
-        $this->assertEqual($this->dbh->pop(), 'SELECT DISTINCT e2.id, COUNT(DISTINCT a2.id) AS a2__0 FROM entity e2 LEFT JOIN album a2 ON e2.id = a2.user_id WHERE (e2.type = 0) GROUP BY e2.id ORDER BY a2__0 DESC, e2.name LIMIT 5');
+        $this->assertEqual($this->dbh->pop(), 'SELECT DISTINCT e2.id, e2.name, COUNT(DISTINCT a2.id) AS a2__0 FROM entity e2 LEFT JOIN album a2 ON e2.id = a2.user_id WHERE (e2.type = 0) GROUP BY e2.id ORDER BY a2__0 DESC, e2.name LIMIT 5');
```
Comment (jaydiablo) [inline tests/Query/MysqlSubqueryTestCase.php]: This query shows how the change in Query.php will affect SQL generated my Doctrine

File: tests/Query/MysqlSubqueryTestCase.php [hunk 5]
```diff
@@ -81,8 +83,9 @@ public function testGetLimitSubquerySupportsOrderByWithAggregateValuesAndColumns
 
         $this->dbh->pop();
 
-        $this->assertEqual($this->dbh->pop(), 'SELECT DISTINCT e2.id, COUNT(DISTINCT a2.id) AS a2__0 FROM entity e2 LEFT JOIN album a2 ON e2.id = a2.user_id WHERE (e2.type = 0) GROUP BY e2.id ORDER BY a2__0, e2.name LIMIT 5');
+        $this->assertEqual($this->dbh->pop(), 'SELECT DISTINCT e2.id, e2.name, COUNT(DISTINCT a2.id) AS a2__0 FROM entity e2 LEFT JOIN album a2 ON e2.id = a2.user_id WHERE (e2.type = 0) GROUP BY e2.id ORDER BY a2__0, e2.name LIMIT 5');
```
Comment (jaydiablo) [inline tests/Query/MysqlSubqueryTestCase.php]: This one too.

**Comment by Rah1x** [comment]
I truely truely appreciate the work you do but how is this not a breaking change? Anyone using MariaDB could potentially have a breakdown as doesnt they never set the option `only_full_group_by` enable by default. Yet mariadb queries would still pass this `if` check.

https://mariadb.com/kb/en/system-variable-differences-between-mariadb-103-and-mysql-57/
https://mariadb.com/kb/en/sql-mode/#only_full_group_by

Ive an older project im maintaining and this took a while to figure out as its not marked in the release notes as a breaking change.
